#Schedule to run daily at 2:00 AM
scheduler:
  cron:
    expression: "0 0 2 * * ?"
    timezone: "America/New_York"
    
#fidelity SFTP
fidelity :
  host : ""
  port : ""
  directory : 
    path : ""
  pooling:
    maxactive: "1"   
    maxidle: "5"
    maxwait: "5"
    mineviction: "300000"
    evictioncheckinterval: "60000"

#Snowflake
snowflake:
  accountName : "a9744066269671-simon_quick_advisors"
  warehouse: "MULESOFT_WH"
  database: "PROD_SIMONQUICK"
  schema: "UTILITY"
  role: "SYSADMIN"